### ISSUE TITLE
Register in METADATA

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/Losses.jl#15]
So... I think LearnBase is ready to be registered.  It's not complete, but what package is?  It's got a ton of content, and I'm using it as the basis for a couple packages (OnlineAI is one).  What do you think?  Should we start a checklist of things to finish before we register?

**Comment by tbreloff** [comment]
We should certainly spend some time on the readme, and it might make sense to have a blog post to summarize some of the design decisions summarizing discussions in the issues.

**Comment by Evizero** [comment]
Ok, maybe you are right. I won't have time to work on this till the end of the week or the beginning of next week, but here's what I would suggest needs to be done:

- [ ] Create a nice and concise readme that outlines the intended use and current functionality
- [ ] Maybe a basic read the docs documentation. I think the readme might be too bloated when really describing how to utilize this package as a backend
- [ ] Check if things other than Loss functions have sufficient tests (the losses are pretty well covered I think)
- [ ] Fix 0.5 issues (if there are any)
- [ ] Move package to JuliaML (I would like the readme to be in place first)

We can leave the read-the-docs documentation unreferenced from the readme for now, since I'll assume we won't really finish it right away. That said, we should at least start with it and I would suggest using .rst mode for all the code documentation goodies.

**Comment by Evizero** [comment]
Also I shall make the transition to BaseTestNext as discussed here

**Comment by tbreloff** [comment]
Good list!

**Comment by Evizero** [comment]
this now depends on LearnBase being in METADATA

**Comment by ahwillia** [comment]
Can we throw an (arbitrary) deadline on this sucker? Maybe Sept 2?

**Comment by Evizero** [comment]
I shall use my next weekend for LearnBase and Losses

**Comment by Evizero** [comment]
We have a few test issue on 0.4. Seems to be related to you new api tests @ahwillia .
We also have quite a low test converage because of all the properties. I would like to double check all the properties and add tests for them (related #43 ) sometime in the next two weeks. as soon as all the test run I'll make the PR to METADATA

**Comment by Evizero** [comment]
Given the timeline on this we may want to entertain the idea of going 0.5+. In that case the current test fails could be ignored

**Comment by ahwillia** [comment]
I say 👍 for dropping 0.4 

Let me know what I can do to help finalize this repo. Just a heads up -- I'm going to be spread a bit thin for the next month or so with conference submissions. I promise I won't disappear entirely.

Thanks for keeping the momentum going on this Christof!

**Comment by Evizero** [comment]
No worries, I too have obligations piling on that I need to take care of. 

Once 0.5 is released I will take care of the remaining issues and make a PR to METADATA

**Comment by ahwillia** [comment]
I don't see a need to wait for the 0.5 release. I vote that we set REQUIRE to `v0.5-` (which includes rc) and then go ahead and make the PR to METADATA.

**Comment by Evizero** [comment]
personally I'd rather take care of the properties first before registering it. That said it will be about a week before I can get back to Julia programming, so if you really want to have it registered asap feel free to do so.

**Comment by Ayush-iitkgp** [comment]
Pkg.add("Losses")
ERROR: unknown package Losses

VERSION
v"0.5.0-rc3+0"

**Comment by Evizero** [comment]
Hi! Yes Losses is not yet registered. I'll get to it this week

**Comment by Evizero** [comment]
Guys. I won't make the property addition before Sunday as I set out. I am leaving in a few hours until Sunday evening and need to catch some sleep first. (Have a proposal deadline on Sunday as well as fate will have it, so that took most of my time). I at least fixed some minor things and the tests run now on 0.5 and 0.6; for what it's worth. I will make the other additions (i.e. properties and tests) next week.

I am ok with registering as is. So please go ahead if you want. I think everything should work fine. It's just that the properties lack tests and might be incomplete at points.

**Comment by tbreloff** [comment]
@Evizero No worries... this is already more complete and tested than most registered packages out there.  There's also no hurry to register from my perspective.

**Comment by Evizero** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6654
